<div class="explorer-more-title">
	<span class="border-explore">
		
	</span>
	<span class="span-text"></span>
</div>
<div class="explorer-more-content">
	<div class="row-explore-left">
		<div class="content-img">
			<a class="link-img" href="#" title="">
				<img src="../../../../../../../skin/frontend/rwd/default/images/mainpage_exploremore_banners_03.jpg">
			</a>
		</div>
		<div class="content-detail">
			<p class="cms_text">
				<span>DESIGN YOUR JEWELLERY</span>
				<br>If you can't find your dream jewellery in any store, you are at the right address! GLAMIRA can custom make any style that you are looking for.
			</p>
		</div>
		<div class="content-link">
			<a href="#" title="">aaaaa</a>
		</div>
	</div>
	<div class="row-explore-center">
		<div class="content-img">
			<a class="link-img" href="#" title="">
				<img src="../../../../../../../skin/frontend/rwd/default/images/mainpage_exploremore_banners_05.jpg">
			</a>
		</div>
		<div class="content-detail">
			<p class="cms_text">
				<span>ASK AN EXPERT</span>
				<br>Tell GLAMIRA what you need and our jewellery specialists will go through thousands of unique designs for you to find the perfect jewellery for your special occasion.
			</p>
		</div>
		<div class="content-link">
			<a href="#" title="">aaaaa</a>
		</div>
	</div>
	<div class="row-explore-right">
		<div class="content-img">
			<a class="link-img" href="#" title="">
				<img src="../../../../../../../skin/frontend/rwd/default/images/mainpage_exploremore_banners_07.jpg">
			</a>
		</div>
		<div class="content-detail">
			<p class="cms_text">
				<span>MEN’S JEWELLERY</span>
				<br>Glamira offers a new definition of style, smartness and delicacy for men’s jewellery. Men who are very fond of their appearance will find everything they need to look attractive.
			</p>
		</div>
		<div class="content-link">
			<a href="#" title="">aaaaa</a>
		</div>
	</div>
</div>