<div class="trung-free-ship container">
	<div class="trung-block-left">
		<div class="top-head">
			<div class="new-top-head">
				<p class="trung-xyz">
					<span class="checked_icon">&nbsp;&nbsp;</span>Free Shipping
				</p>
				<p class="trung-xyz">
					<span class="checked_icon_red">&nbsp;&nbsp;</span><a href="#">60 day return policy
				</p>
			</div>
		</div>
	</div>
	<div class="trung-block-right">
		
	</div>
</div>