<div class="trung-free-ship container">
	<div class="trung-block-left">
		<div class="top-head">
			<div class="new-top-head">
				<p class="trung-xyz">
					<span class="checked_icon">&nbsp;&nbsp;</span>Free Shipping
				</p>
				<p class="trung-xyz">
					<span class="checked_icon_red">&nbsp;&nbsp;</span><a href="#">60 day return policy
				</p>
			</div>
		</div>
	</div>
	<div class="trung-block-right">
		<ul class="links">
            <li class="first last">
            	<a href="#" title="Log In/Sign Up">Log In/Sign Up</a>
            </li>
        </ul>
        <ul class="menu-action">
        	<li class="compare-link">        		
    			<span class="new_heard_icon">&nbsp;</span>
    			<a class="top-heard" href="#">
    				<span class="text">SAVED ITEMS</span> 
    				<span class="total_shortlist">(0)</span>
    			</a> 
        	</li>
        	<li class="cart-link cart-link-hover">
        		<a href="#">
        			<span class="new_cart_icon">&nbsp;</span>
        			<span class="text">Shopping Bag </span>
        			<span class="count_cart">(0)</span>
        		</a>
        	</li>
        </ul>
	</div>
</div>