<div class="news-content">
	<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 nopad news-content-left">
		<ul class="row-explore-content">
			<li>
				<div class="content-img">
					<a class="link-img" href="#" title="">
						<img src="../../../../../../../skin/frontend/rwd/default/images/valentinesdaydeals_smallbanner.jpg">
					</a>
				</div>
				<div class="content-detail">
					<p class="cms_text">
						<span>Valentine’s Day Deals</span>
						<br>Your soulmate is your perfect fit, and that's what everyone wants! Show them your deepest emotions with our amazing jewellery at a discounted price!
						<span class="surprise_sale"> Up to 70% off.</span></p>
				</div>
				<div class="content-link">
					<a href="#" title="">aaaaa</a>
				</div>
			</li>
			<li>
				<div class="content-img">
					<a class="link-img" href="#" title="">
						<img src="../../../../../../../skin/frontend/rwd/default/images/homepage_new_19.jpg">
					</a>
				</div>
				<div class="content-detail">
					<p class="cms_text">
						<span>PEARL JEWELLERY</span>
						<br>Cherished as the most elegant gift to a special one, pearls are one of a kind natural wonders.
					</p>
				</div>
				<div class="content-link">
					<a href="#" title="">aaaaa</a>
				</div>
			</li>
		</ul>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 nopad news-content-right">
		<ul class="row-explore-content">
			<li>
				<div class="content-img">
					<a class="link-img" href="#" title="">
						<img src="../../../../../../../skin/frontend/rwd/default/images/mainpage_smallbanner_social.jpg">
					</a>
				</div>
				<div class="content-detail">
					<p class="cms_text">
						<span>ENTER GLAMIRA’S PRIZE DRAW</span>
						<br>Order any GLAMIRA product between Jan 16 and Feb 5 for the chance to 
						<span class="title">win a GLAMIRA voucher with 50%</span> 
						of what you have spent on the product! 
						<span class="social_link">View Campaign Details
							<span class="icon">&nbsp;</span>
						</span></p>
				</div>
				<div class="content-link">
					<a href="#" title="">aaaaa</a>
				</div>
			</li>
			<li>
				<div class="content-img">
					<a class="link-img" href="#" title="">
						<img src="../../../../../../../skin/frontend/rwd/default/images/homepage_new_12.jpg">
					</a>
				</div>
				<div class="content-detail">
					<p class="cms_text">
						<span>MEN’S JEWELLERY</span>
						<br>Glamira offers a new definition of style, smartness and delicacy for men’s jewellery. Men who are very fond of their appearance will find everything they need to look attractive.
					</p>
				</div>
				<div class="content-link">
					<a href="#" title="">aaaaa</a>
				</div>
			</li>
		</ul>
	</div>
	
</div>