<div class="prod-content">
	<div class="landing-page">
		<div class="landing-block landing-image">
			<a class="link-img" href="#" title="">
				<img clas="img" src="../../../../../../../skin/frontend/rwd/default/images/banner_homepage_new_03.jpg">
			</a>
		</div>
		<div class="landing-block landing-textlink">
			<div class="landing-textlink-content">
				<ul>
					<li>
						<a href="#" title="Diamond Engagement Rings">Diamond Engagement Rings</a>
					</li>
					<li>
						<a href="#" title="Gemstone Engagement Rings">Gemstone Engagement Rings</a>
					</li>
					<li>
						<a href="#" title="Engagement Ring Catalog">Engagement Ring Catalog</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="landing-page">
		<div class="landing-block landing-image">
			<a class="link-img" href="#" title="">
				<img clas="img" src="../../../../../../../skin/frontend/rwd/default/images/banner_homepage_new_05.jpg">
			</a>
		</div>
		<div class="landing-block landing-textlink">
			<div class="landing-textlink-content">
				<ul>
					<li>
						<a href="#" title="Women Wedding Rings">Women Wedding Rings</a>
					</li>
					<li>
						<a href="#" title="Men Wedding Rings">Men Wedding Rings</a>
					</li>
					<li>
						<a href="#" title="Wedding Ring Catalog">Wedding Ring Catalog</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="landing-page">
		<div class="landing-block landing-image">
			<a class="link-img" href="#" title="">
				<img clas="img" src="../../../../../../../skin/frontend/rwd/default/images/banner_homepage_new_07.jpg">
			</a>
		</div>
		<div class="landing-block landing-textlink">
			<div class="landing-textlink-content">
				<ul>
					<li>
						<a href="#" title="Necklaces">Necklaces</a>
					</li>
					<li>
						<a href="#" title="Earrings">Earrings</a>
					</li>
					<li>
						<a href="#" title="Bracelets">Bracelets</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>