<div class="four-blocks">
	<div class="four-blocks-content">
		<div class="icon-customise block">
			<div class="icon-left">
				<div class="icon-img">
					<img src="../../../../../../../skin/frontend/rwd/default/images/icon-customise.png">
				</div>
			</div>
			<div class="content-right">
				<div class="content-title">
					customise your jewellery
				</div>
				<div class="content-detail">
					All GLAMIRA products are fully customisable to your preferences.
				</div>
			</div>
		</div>
		<div class="icon-guaranteed block">
			<div class="icon-left">
				<div class="icon-img">
					<img src="../../../../../../../skin/frontend/rwd/default/images/icon-guaranteed.png">
				</div>
			</div>
			<div class="content-right">
				<div class="content-title">
					100% Satisfaction Guaranteed
				</div>
				<div class="content-detail">
					We are committed to your satisfaction. If you are not happy with your choice, return it within 60 days.
				</div>
			</div>
		</div>
		<div class="icon-service block">
			<div class="icon-left">
				<div class="icon-img">
					<img src="../../../../../../../skin/frontend/rwd/default/images/icon-delivery.png">
				</div>
			</div>
			<div class="content-right">
				<div class="content-title">
					Free Insured Delivery
				</div>
				<div class="content-detail">
					GLAMIRA guarantees safe delivery of each order.
				</div>
			</div>
		</div>
		<div class="icon-delivery block">
			<div class="icon-left">
				<div class="icon-img">
					<img src="../../../../../../../skin/frontend/rwd/default/images/icon-service.png">
				</div>
			</div>
			<div class="content-right">
				<div class="content-title">
					Customer-Oriented Service
				</div>
				<div class="content-detail">
					Call us at 0800 808 5745. Our customer support team will be happy to assist you.
				</div>
			</div>
		</div>
	</div>
</div>