<div class="trung-top-header-container">
	<div class="trung-campaign-header-info">
		<div class="container">
			<div class="trung-campaign-info-content">
				<a href="#" title="GET 10% OFF on all garnet jewellery!">
					<span class="campaign-info-text">
						<span>GET 10% OFF on all garnet jewellery!</span>
						<span class="campaign-info-link">
							<span class="hide-on-mobile"> | </span>Shop Now 
							<span class="icon">&nbsp;</span>
						</span>
					</span>
				</a>
			</div>
		</div>
	</div>
</div>